[package]
name = "jumpy-core"
version = "0.4.3"
authors = ["The Fish Fight Game & Spicy Lobster Developers"]
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
fishsticks = { git = "https://github.com/fishfight/fishsticks", default-features = false, features = ["gilrs"] }
macroquad = { version = "0.3.10" }
hecs = "0.7.1"
serde = { version = "1.0", package = "serde", features = ["derive"] }
serde_json = { version = "1.0" }
toml = "0.5"
async-trait = "0.1.52"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }
wasm-bindgen = "0.2.74"