[book]
authors = ["Carlo Supina", "Srayan Jana", "grufkok", "Micah Tigley"]
language = "en"
multilingual = false
src = "src"
title = "Fish Fight Documentation"

[output.html]
default-theme = "navy"
git-repository-url = "https://github.com/fishfight/FishFight"
git-repository-icon = "fa-github"
