# This action will generate Windows|Linux|MacOS binary releases

name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build_release:
    name: Build release binaries
    runs-on: ${{ matrix.config.os }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-latest, target: "x86_64-unknown-linux-gnu" }
          - { os: macos-latest, target: "x86_64-apple-darwin" }
          - { os: macos-latest, target: "aarch64-apple-darwin" }
          - { os: windows-latest, target: "x86_64-pc-windows-msvc" }
          - { os: windows-latest, target: "i686-pc-windows-msvc" }

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set the release version
        shell: bash
        run: echo "RELEASE_VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV

      - name: Setup Dependencies
        if: matrix.config.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install --allow-unauthenticated -y -qq \
           libasound2-dev libgl1-mesa-dev libx11-dev libxi-dev

      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          target: ${{ matrix.config.target }}

      - name: Build
        uses: actions-rs/cargo@v1
        env:
          SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
          RUSTFLAGS: -L /usr/lib/x86_64-linux-gnu
        with:
          command: build
          args: --release --locked --target ${{ matrix.config.target }}

      - name: Prepare artifacts [Windows]
        shell: bash
        if: matrix.config.os == 'windows-latest'
        run: |
          release_dir="fishfight-${{ env.RELEASE_VERSION }}"
          artifact_path="fishfight-${{ env.RELEASE_VERSION }}-${{ matrix.config.target }}.zip"
          echo "ARTIFACT_PATH=$artifact_path" >> $GITHUB_ENV
          mkdir $release_dir
          cp target/${{ matrix.config.target }}/release/fishfight.exe $release_dir/
          strip $release_dir/fishfight.exe
          find assets -name "*.schema.json" -exec rm -f {} \;
          cp -R assets/ $release_dir/
          7z a -tzip $artifact_path $release_dir/

      - name: Prepare artifacts [Unix]
        shell: bash
        if: matrix.config.os != 'windows-latest'
        run: |
          release_dir="fishfight-${{ env.RELEASE_VERSION }}"
          artifact_path="fishfight-${{ env.RELEASE_VERSION }}-${{ matrix.config.target }}.tar.gz"
          echo "ARTIFACT_PATH=$artifact_path" >> $GITHUB_ENV
          mkdir $release_dir
          cp target/${{ matrix.config.target }}/release/fishfight $release_dir/
          strip $release_dir/fishfight || true
          find assets -name "*.schema.json" -exec rm -f {} \;
          cp -R assets $release_dir
          tar -czvf $artifact_path $release_dir/

      - name: Deploy | Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_PATH }}
          path: ${{ env.ARTIFACT_PATH }}
          if-no-files-found: error

  publish_release:
    name: Create and Publish GitHub Release
    needs: build_release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Artifacts
        uses: actions/download-artifact@v2

      - name: Set the release version
        shell: bash
        run: echo "RELEASE_VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV

      - name: Generate Checksums
        run: for file in fishfight-*/fishfight-*; do openssl dgst -sha256 -r "$file" | awk '{print $1}' > "${file}.sha256"; done

      - name: Publish Release
        uses: svenstaro/upload-release-action@v2
        with:
          release_name: Release ${{ env.RELEASE_VERSION }}
          file: fishfight-*/fishfight-*
          file_glob: true
          overwrite: true
          body: "FishFight ${{ env.RELEASE_VERSION }} üêü"
          tag: ${{ github.ref }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
